version: '3.7'
# https://www.pluralsight.com/guides/packaging-a-django-app-using-docker-nginx-and-gunicorn
# https://stackoverflow.com/questions/51557216/django-nginx-docker-gunicorn-cant-reach
# https://ruddra.com/serve-static-files-by-nginx-from-django-using-docker/y
services:
  web:
    build: .
    command: sh -c "python manage.py makemigrations &&
                    python manage.py migrate &&
                    python manage.py collectstatic --noinput --clear &&
                    gunicorn django_auto_deploy.wsgi:application --bind 0.0.0.0:${APP_PORT}"
    volumes:
      - .:/code
      - .static/:/static
    ports:
      - "8000:8000"
    restart: "always"