name: Python application

on: [push]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - name: Checkout code # checking our the code at current commit that triggers the workflow
      uses: actions/checkout@v2
    - name: Setup python environment # setting python environment to 3.x
      uses: actions/setup-python@v2
      with:
        python-version: '3.x' 
    - name: Starting Docker
      run: docker-compose up
