name: Python application

on: [push]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - name: Checkout code # checking our the code at current commit that triggers the workflow
      uses: actions/checkout@v2
    - name: Setup python environment # setting python environment to 3.x
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Creating Virtual Environment
      run: /
        python3 -m pip install --upgrade pip
        pip3 install virtualenv
        virtualenv djangoenv
        source djangoenv/bin/activate 
    - name: Install dependencies
      run: /
        pip3 install gunicorn psycopg2-binary
        pip3 install -r requirements.txt
    - name: Run migrations
      run: python manage.py migrate
    - name: Lunching Apllication
      run: python3 ./manage.py runserver 0.0.0.0:8000
    # - name: Run tests
    #   run: python3 manage.py test